config/routes.rb
Rails.application.routes.draw do

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  

  resources :users
  resources :posts do 
      resources :comments, shallow: true, only: [:create, :destroy]
    end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
# scope :starts_with_h, -> { where("body LIKE ?", "H%") }
#select * from posts where body like "p%"

	belongs_to :user
	has_many :comments

	validates :body, presence: true
	# before_create :mixxy

	# 	def mixxy
	# 		self.body = body + ":-)"	
	# 	end

	has_attached_file :milktar, styles:
	{ medium: "300x300>", thumb: "100x100>" }
	# ,default_url: "/images/:style/missing.png"
	
	validates_attachment_content_type :milktar,
	content_type: /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
	# has_secure_password
	# validates_confirmation_of :password
	# validates_presence_of :password, on: :create


	attr_accessor :password
	validates_confirmation_of :password
	before_save :encrypt_password


	def encrypt_password
		self.password_salt = BCrypt::Engine.generate_salt
		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	end

	def self.authenticate(email,password)
	user = User.where(email: email).first
		if user && user.password_hash == BCrypt::Engine.hash_secret(password,user.password_salt)
		user
		else
		nil
		end
	end

# scope :with_email_andre, -> { 
# 	where(email: "andre@gmail.com") 
# }
# scope :with_special_name, lambda { |name| where(username: name) }
	
	# has_many :posts
	# has_many :comments

	validates_presence_of :email, :username, :password
	# #works everytime you save email to db (so creating and updating)
	# validates :email, uniqueness: true
	validates :username, uniqueness: true
	# validates :password, confirmation: true, presence: true
	# validates :username, length: {in: 6..30}
	# validates :password, length: {in: 6..30}

	has_attached_file :avatar, :styles =>
	{ :medium => "300x300>", :thumb => "100x100>" },
	:default_url => "/images/:style/missing.png"
	
	validates_attachment_content_type :avatar,
	:content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    # protect_from_forgery with: :null_session

  # private
  # 	def current_user
  # 		if session[:user_id]
  # 			User.find(session[:user_id])
  # 		else
  # 			nil
  # 		end
  # 	end
    # session[:user_id] ? User.find(session[:user_id]) : nil
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		puts params.inspect
		# @comment = Comment.create ({body: params[:body]})
		@comment = Comment.create({ body: params[:comment][:body], user_id: session[:user_id], post_id: params[:post_id]})
		redirect_to post_path(params[:post_id])
		#need to pass in the id of the post it is in response to, and the id of the user who made the comment
	end



	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		#ADD IF ELSE SO THAT ONLY USER WHO WROTE COMMENT CAN DELETE IT
		redirect_to post_path(@comment.post.id)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		if session[:user_id]
			@posts = Post.all
			# @posts = Post.starts_with_h
		else
			flash[:alert] = "You must be logged in to view posts"
			redirect_to login_path
		end		
	end

	def create
		@post = Post.new(post_params)
		# @user = User.find(session[:user_id])
		# @user.posts << @post

		@post.user_id = session[:user_id]
		@post.save
		# @post = Post.create({ body: params[:post][:body], user_id: session[:user_id]})
			redirect_to posts_path #NECESSARY for response
		
			# respond_to do |format|
			# format.js
			# format.html do 
			# 	redirect_to posts_path
			# end
			# end
	end

	def new
		if session[:user_id]
			@post = Post.new
		else
			flash[:alert] = "You must be logged in to create posts"
			redirect_to login_path
		end		
	end

	def show
		if session[:user_id]
			@post = Post.find params[:id]
			# @post = Post.all
			# @comments = Post.all.comments
		else
			flash[:alert] = "You must be logged in to view posts"
			redirect_to login_path
		end		
	end


	def update
		@post = Post.find(params[:id])
		@post.update_attributes params[:body]
		redirect_to edit_post_path
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end
	
	private
	def post_params
		params.require(:post).permit(:body, :user_id, :milktar)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user = User.authenticate(params[:email],params[:password])
		if @user
			flash[:notice] = "Successful Login"
			session[:user_id] = @user.id
			redirect_to users_path
		else
			flash[:alert] = "Incorrect Login Info"
			render :new
		end
		
		# @user = User.where(email: params[:email]).first
		# if @user && @user.password == params[:password]
		# 	session[:user_id] = @user.id
		# 	flash[:notice] = "Successful Login" 
		# 	redirect_to users_path
		# else
		# 	flash[:alert] = "Incorrect Login Info"
		# 		render :new #renders page again
		# end
	end
		


		# @user = User.find_by_email(params[:email])
		# 	if user && user.authenticate (params[:password])
		# 		session[:user_id] = user.id
		# 		redirect_to users_path, :notice => "Welcome back, #{user.email}"
		# 	else
		# 	flash[:alert] = "Incorrect Login Info"
		# 	render :new
		# 	end
		

	

 	def destroy
 		session[:user_id] = nil
 		flash[:notice] = "You are now signed out"
 		redirect_to users_path
 	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		if session[:user_id]
			@users = User.all
			# @users = User.with_email_andre 
				#testing scopes 
			# @users = User.with_special_name("badu")
		else
			flash[:alert] = "You must be logged in to view users."
			redirect_to login_path
		end		
	end

	def create
		@user=User.new(user_params)
		if @user.save 
			flash[:notice] = "Your account was created successfully."
			redirect_to users_path
		else
			flash[:alert] = "There was a problem saving your account."
			redirect_to new_user_path
		end	
	


		# if User.find_by email: params[:user][:email]  
		#  	flash[:alert] = "This email address is already signed up for an account."
		# 	redirect_to login_path
		# elsif User.find_by username: params[:user][:username]
		# 	flash[:alert] = "That username is already in use, please select another."
		# 	redirect_to login_path
		# else
			# @user = User.create params[:user] 
			# @user = User.new(params[:user])
			# @user = User.new(user_params)
			# @user.save

				# if @user.save
				# #@user = User.create (user_params)  #trying out private method below
				# redirect_to users_path
				# else 
				# 	render :new
				# end
	end
	# end
		

		#WHY NEW AND NOT CREATE? WOULDN'T I ALSO NEED A SAVE HERE?
	def new
		@user = User.new
	end

	def show
		@user = User.find params[:id]
	end
	
	def edit
    # finds user with id of params[:id]
    @user = User.find params[:id]
  	end

	def update
		@user = User.find params[:id]
		@user.update params[:user]
		redirect_to edit_user_path(@user)
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end

	private
	def user_params
		params.require(:user).permit(:email, :username, :password, :password_confirmation, :avatar)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def body_target
		controller.controller_name + "_" + controller.action_name
	end	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	# def reverse_text(text)
	# 	text.to_s.reverse
	# end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lady</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body class="<%= body_target %>"> <!-- this is a helper that i made-->
 <% if flash[:notice] %>
     	<h1 class="flash-notice">
     		<%= flash[:notice] %>
   	 	</h1>
	<% end %>
<% if flash[:alert] %>
		<h1 class="flash-alert">
		    <%= flash[:alert] %>
		</h1>
<% end %>
<nav>



<!-- if user is logged in, they see all the links except the log-in one 
  if they are not logged in, they see all links except the log-out
logged-in content: all links but log-in
logged-out content -->





</nav>

<%= yield %>


</body>
</html>

app/views/posts/create.js.erb
$(document).ready(function(){
	// $("#posty").html("<%= @post %>")

	$("#posty").append("<%= @post.body %>")
})

app/views/posts/index.html.erb
<div id="all_posts">
<%= link_to 'Log Out', logout_path, method: :delete%>
<%=link_to "View All Users", users_path%>
<%= link_to "Make New Post", new_post_path%>

<% @posts.order(created_at: :desc).each do |p| %>
	<br>
 	<% if p.user %>
 		<h1><a href="/posts/<%= p.id %>" id="nodec"><%= p.user.username %></a></h1>
 	<% end %>
 	<%= image_tag p.milktar.url(:thumb) if p.milktar.present?   %>
 	<p><%= p.body %></p>
 	<p><%= distance_of_time_in_words(Time.now, p.created_at, include_hours: true)%> ago</p>
	
 	<hr>
	<% end %>
</div>
<!-- Site for a plug-in to try to make time more accurate, show 
48 hours" instead of "2 days" http://clojurehackers.com/p/shripadk/dotiw -->
	

app/views/posts/new.html.erb
NEW POST

<%= form_for @post,  :url => posts_path, :html => { :multipart => true } do |f| %>
  <%=f.label :body %>
  <%=f.text_area :body, :size => "60%x5%" %>
  <%= f.file_field :milktar %>
  <%=f.submit :create %>
<% end %>

<hr>
<div id="posty">

</div>

app/views/posts/show.html.erb
<%=link_to "View All Users", users_path%>
<%= link_to 'Log Out', logout_path, method: :delete%>
<%= link_to "Make New Post", new_post_path%>

<h1> Show Posts Page</h1>

<strong>Post: </strong>
<%= @post.body %> <br>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", @post, method: :delete, data: {confirm: "Are you sure you want to delete this post?"} %> <br>
<strong>Created At: </strong>
<%= @post.created_at.strftime("at %I:%M%p on %m/%d/%Y") %> <br>
<br>

<strong>Leave A Comment: </strong>
<%= form_tag post_comments_path(@post.id), method: :post do %>
	<%= text_area :comment, :body, size: "60%x5%" %>
	<%= hidden_field_tag(:post_id, @post.id) %>
	<%= button_tag :create %>
<% end %>

<% @post.comments.order(created_at: :desc).each do |c|%> <br> 
	<p><%= c.body %></p>
	<p><strong>from: <%= c.user.username %></strong></p>
	<p><%= c.created_at.strftime("at %I:%M%p on %m/%d/%Y") %></p>
	<%= link_to "Delete", comment_path(c), method: :delete, remote:true, data: {confirm: "Are you sure you want to delete this comment?"} %>
	<hr>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user do |form| %>
	<%=form.label :email %>
	<%=form.text_field :email %>
	<%=form.label :username %>
	<%=form.text_field :username %>
	<%=form.label :password %>
	<%=form.text_field :password %>
	<%=form.submit :edit %> 
<% end %>

<!-- why can't line 6 submit straight to the update action in the users controller? why does it have to go through edit, and how does that link to the update action?
	rails user/id/edit automatically goes to the user controller action update (as you cann see in rails/info/routes)-->

app/views/users/index.html.erb
<div id ="index_body">
<%=link_to "View All Posts", posts_path%>
<%= link_to 'Log Out', logout_path, method: :delete%>
<%= link_to "Make New Post", new_post_path%>


<div id="user_ind">
<% @users.order(created_at: :desc).each do |u| %>
	<%= image_tag u.avatar.url(:thumb) %>
	<p><strong>Username:</strong> <a href="/users/<%= u.id %>" id="nodec"><%= u.username %> </a></p>
	<p><strong>Email:</strong>  <%= u.email %></p>
	<hr>
	<% end %>
</div>


</div>

app/views/users/new.html.erb
 <%= form_for @user,:url => users_path,
:html => { :multipart => true } do |f| %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :username %>
<%= f.text_field :username %>
<%= f.label :password %>
<%= f.text_field :password %>
<%= f.label :password_confirmation %>
<%=f.text_field :password_confirmation %>
<%= f.file_field :avatar %>
<%= f.submit :create %>
<% end %>

<% if @user.errors.full_messages.any? %>
  <ul>
    <% @user.errors.full_messages.each do |error_message| %>
      <li><%= error_message%></li> <br />
    <% end %>
  </ul>
<% end %>

app/views/users/show.html.erb
<%=link_to "Edit User Info", edit_user_path(@user.id) %>
<%=link_to "View All Posts", posts_path%>
<%=link_to "View All Users", users_path%>
<%= link_to 'Log Out', logout_path, method: :delete%>


<h1> Show User Page</h1>

<strong>Username: </strong>
<%= @user.username %> <br>
<strong>Email: </strong>
<%= @user.email %> <br>